# Generated by Django 4.1 on 2022-08-12 16:55

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.models.get_timestamp_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='animalcategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
