# Generated by Django 4.1 on 2022-08-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_animalcategory_image_alter_animalcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='first_offer',
            field=models.IntegerField(default=1, verbose_name='Первое предложение кол-ва'),
        ),
        migrations.AddField(
            model_name='product',
            name='second_offer',
            field=models.IntegerField(default=1, verbose_name='Второе предложение кол-ва'),
        ),
    ]
