# Generated by Django 4.1 on 2022-08-13 11:48

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_first_offer_product_second_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.models.get_timestamp_path, verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='measure',
            field=models.CharField(choices=[('кг.', 'кг.'), ('л.', 'л.'), ('шт.', 'шт.'), ('гр.', 'гр.')], max_length=20),
        ),
    ]
