# Generated by Django 4.1 on 2022-08-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_brand_image_alter_productcategory_measure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('tel', models.CharField(max_length=17)),
                ('petName', models.CharField(max_length=50)),
            ],
        ),
    ]
