# Generated by Django 4.1 on 2022-08-17 04:53

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=catalog.models.get_timestamp_path, verbose_name='Изображение')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Контент')),
                ('time_of_read', models.IntegerField(verbose_name='Время чтения в минутах')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='feedback',
            name='content',
            field=models.TextField(verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='petName',
            field=models.CharField(max_length=50, verbose_name='Имя питомца'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='tel',
            field=models.CharField(max_length=17, verbose_name='Телефон'),
        ),
    ]
