# Generated by Django 4.1 on 2022-08-28 06:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_article_alter_feedback_content_alter_feedback_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='owner',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=10, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='tel',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='Телефонный номер должен быть в формате +3753363785379', regex='^\\+375\\d{9,9}$')], verbose_name='Телефон'),
        ),
    ]
