# Generated by Django 4.1 on 2022-09-05 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_article_owner_alter_feedback_name_alter_feedback_tel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='article',
            name='owner',
            field=models.CharField(blank=True, default=1, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='tel',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='Введите номер в формате +3753363785379', regex='^\\+375\\d{9,9}$')], verbose_name='Телефон'),
        ),
    ]
